version: "3.7"
services:
  app:
    build:
      args:
        user: rfid_sys
        uid: 1000
      context: ./.docker
      dockerfile: Dockerfile
    image: uni_erp
    container_name: rfid-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./src:/var/www
      - ./.docker/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      - rfid_sys
      - db_app-shared
    dns:
      - 8.8.8.8

  nginx:
    image: nginx:1.17-alpine
    container_name: rfid_sys-nginx
    restart: unless-stopped
    ports:
      - 8090:80
    volumes:
      - ./src:/var/www
      - ./.docker/nginx:/etc/nginx/conf.d
    networks:
      - rfid_sys

networks:
  rfid_sys:
    driver: bridge
  db_app-shared:
    external: true

